config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, on: :collection
  end
  resources :categories
  resources :static_pages, only: :index
  root 'static_pages#index'
end

app/models/category.rb
class Category < ActiveRecord::Base  
  validates :name, presence: true
  extend FriendlyId
  friendly_id :name, :use => :slugged

  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :name, :body, presence: true
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, :use => :slugged

  validates :body, :title, presence: true
  has_many :comments, validate: true
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  expose(:category, finder: :find_by_slug, attributes: :category_params)
  expose(:categories)
  
  def new
  end

  def create

    if category.save
      flash.notice = "#{category.name} Category created"
      redirect_to categories_path
    else
      render :new
    end
  end

  def show
  end

  def index
  end

  def edit
    if category.save
      flash.notice = "#{category.name} Category updated"
    else 
      flash.notice = "#{category.name} Could not save. Please throw computer at wall."
    end
  end

  def update
    if category.save
      flash.notice = "#{category.name} Category updated"
      redirect_to categories_path
    else
      flash.notice = "#{category.name} Could not save. Please throw computer at wall."
      render :edit
    end
  end

  def destroy
    category.destroy
    if category.destroy
      flash.notice = "#{category.name} category deleted"
    end
    redirect_to categories_path
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  expose(:post) { Post.friendly.find(params[:post_id] || comment_params[:post_id]) }
  expose(:comment, attributes: :comment_params)

  def new
  end

  def create
    post.comments.build(comment_params)
    if post.save
      flash[:success] = "Comment saved successfully."
      redirect_to post
    else
      flash[:error] = "Sorry! An error has occurred in creation of your comment."
      render :new
    end
  end

  def edit
  end

  def update
    if comment.save
      redirect_to post
    else
      render :edit
    end
  end

  def destroy
    comment.destroy

    redirect_to post
  end

  private

  def comment_params
    params.require(:comment).permit(:name, :body, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  expose(:post, finder: :find_by_slug, attributes: :post_params)
  expose(:posts)
  expose(:categories)
  expose(:comment) { post.comments.build }
  def show
  end

  def index
  end

  def new
  end

  def create
    if post.save
      flash[:success] = "Post has been created successfully."
      redirect_to post
    else
      flash[:error] = "Sorry! An error has occurred in creation of the post."
      render :new
    end
  end

  def edit
  end

  def update
    if post.save
      flash[:success] = "Post has been updated successfully."
      redirect_to post 
    else
      render :edit
    end
  end

  def destroy
    post.destroy
    flash[:success] = "Post has been deleted successfully."
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :category_id, :published)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def bootstrap_class_for(flash_type)
	    case flash_type
	      when "success"
	        "alert-success"   # Green
	      when "error"
	        "alert-danger"    # Red
	      when "alert"
	        "alert-warning"   # Yellow
	      when "notice"
	        "alert-info"      # Blue
	      else
	        flash_type.to_s
	    end
	end

end

app/helpers/posts_helper.rb
module PostsHelper
	def change_timestamp(post)
		if post.created_at != post.updated_at
			"Updated at #{post.updated_at.strftime("%d/%m/%y at %H:%M")}"
		end
	end
end

app/views/categories/_form.html.erb
<% category.errors.full_messages.each do |error_message| %>
	<div class="alert warning">
		<%= error_message %>
	</div>
<% end %>

<%= form_for category do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/categories/index.html.erb
<%= link_to 'Add Category', new_category_path, class: 'btn btn-primary' %>

<% categories.each do |category| %>
	<div>
		<%= link_to category.name, {action: :show, id: category} %>
		<span>
			<%= link_to 'edit', {action: :edit, id: category}, class:'btn-xs btn-primary'%>
			<%= link_to 'delete', {action: :destroy, id: category}, class:'btn-xs btn-danger', method: :delete,  data: { confirm: 'Are you sure in deleting this', action: :destroy } %>
		</span>
	</div>	

<% end %>	

app/views/categories/show.html.erb
<%= category.name%>

app/views/comments/_comments.html.erb
<% if post.comments.length>0 %>
	<h5> Comments </h5>
	<% post.comments.each  do |comment|%>
		<div class="panel panel-default">
			<div class="panel-heading">
			    <h3 class="panel-title">
			    	<%= comment.name %>
			    </h3>
			</div>
		  	<div class="panel-body">
		    	<%= comment.body %>
		  	</div>
		  	<div class="panel-footer">
		  		Created on: <%= comment.created_at.strftime("%d/%m/%y at %H:%M") %>
		  	</div>
		</div>
	<% end %>
<% else %>
	<i class="text-info">
		<%= 'No Comments made so far' %>
		<br/><br/>	 
	</i>	
<% end %>

app/views/comments/_form.html.erb
<div class="panel panel-primary"> 
	<div class="panel-heading">Wanna make a comment... Here you go !!</div>
	<div class="panel-body">
		<%= form_for [post,comment] do |f| %>
		  <div class="form-group">
		    <%= f.label 'Comment Name' %>
		    <%= f.text_field :name, class: "form-control", required: true%>
		  </div>
		  <div class="form-group">
		    <%= f.label 'Comment' %>
		    <%= f.text_area :body, class: "form-control"%>
		  </div>
		  <%= f.submit class: 'btn btn-primary' %>
		<% end %>
	</div>	
</div>	

app/views/comments/_new.html.erb
<%= render './comments/form' %>

app/views/comments/show.html.erb
<!-- Listing all the available comments -->
<%= render 'comments' , collection: post.comments %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWorkshop</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/nav' %>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<h5 class="text-center"> 
		Here you can make a post, which you which in the categories available. 
</h5>
<!-- Form to create the post -->
<%= form_for post do |f| %>
	<div class="form-group">
	    <%= f.label 'Title of the post' %>
	    <%= f.text_area :title, class: "form-control" %>
	</div>
	<div class="form-group">
	    <%= f.label 'Content of the post' %>
	    <%= f.text_area :body, class: "form-control" %>
	</div>
	<div class="form-group">
	    <%= f.label 'Category of the post' %>
	    <%= f.collection_select(:category_id, categories, :id, :name, :prompt => 'Select category') %>
	</div>
	<div class="form-group">
	    <%= f.label 'Do you want to publish this post' %>
        <%= f.radio_button(:published, true) %>
		<%= f.label(:published_true, 'Yes') %>
		<%= f.radio_button(:published, false) %>
		<%= f.label(:published_false, 'No') %>
	</div>
  	<%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<section> 
	<%= render 'shared/flash_messages', flash: flash %> 
	<div>
		<h5 class='pull-left'> Here are the posts created so far</h5>
		<%= link_to 'create post', new_post_path, class:'btn-lg btn-primary pull-right' %>
	</div>
	<br/><br/>
	
	<!-- listing the posts if available -->
	<% if posts.length>0 %>
		<% posts.each do |post| %>
			<div>
				<%= link_to post.title, post_path(post), class:'col-xs-12' %>
				<span>
					<%= link_to 'edit', {action: :edit, id: post}, class:'btn-xs btn-primary'%>
					<%= link_to 'delete', {action: :destroy, id: post}, class:'btn-xs btn-danger', method: :delete,  data: { confirm: 'Are you sure in deleting this post', action: :destroy } %>
				</span>
			</div>	
		<% end %>
	<% else %>
		<%= 'Sorry no posts available' %>	
	<% end %>
</section>

app/views/posts/new.html.erb
<%= render 'form' %>
<%= render 'shared/flash_messages', flash: flash %> 

app/views/posts/show.html.erb
<section>
	<%= render 'shared/flash_messages', flash: flash %> 
	<div>
		<div class="label label-warning">  
			Category Name:
			<%=  post.category.name %>
		</div>
		<br/>
		<div class="label label-warning"> 
			Published :
			<%= post.published %>
		</div>
		<br/><br/>
		<h5> Title: <%= post.title%> </h5>
		<p> Content: <%= post.body %> </p>
	</div>
	<!-- Listing all the available comments -->
	<%= render './comments/comments' , collection: @comments %>
	<!-- Adding comments to the posts -->
	<%= render './comments/new' , collection: post.comments %>

</section>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade in">
    <button type="button" class="close" data-dismiss="alert">
    	<span aria-hidden="true">&times;</span>
    	<span class="sr-only">Close</span>
     </button>
    <%= message %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'MD Workshop', root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Posts', posts_path %></li>
        <li><%= link_to 'Categories', categories_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/static_pages/index.html.erb
<h1>Rails Workshop</h1>